import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider>
          <nav style={{ backgroundColor: '#171717', borderBottom: '1px solid #262626' }}>
            <div className="container mx-auto px-6 py-4">
              <div className="flex items-center space-x-8">
                <Link href="/" className="nav-link">
                  Dashboard
                </Link>
                <Link href="/products" className="nav-link">
                  Products
                </Link>
                <Link href="/consumers" className="nav-link">
                  Consumers
                </Link>
                <Link href="/licenses" className="nav-link">
                  Licenses
                </Link>
                <Link href="/lookup" className="nav-link">
                  License Lookup
                </Link>
              </div>
            </div>
          </nav>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
